#!/usr/bin/env dash
#
# This file is part of OpenMediaVault.
#
# @license   https://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    ${GITHUB_USER}
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
	configure)
		########################################################################
		# Make sure the shipped files are executable.
		########################################################################
		chmod 0755 /usr/sbin/omv-immich-ctl

		########################################################################
		# Activate trigger to rebuild workbench configuration files.
		########################################################################
		dpkg-trigger update-workbench

		########################################################################
		# Initialize and migrate configuration database.
		########################################################################
		echo "Updating configuration database ..."
		omv-confdbadm create "conf.service.immich"
		if [ -n "$2" ]; then
			omv-confdbadm migrate "conf.service.immich" "${2}"
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument '$1'" >&2
		exit 1
	;;
esac

exit 0
